### ISSUE TITLE
Request for `firebolt` name

### ISSUE THREAD

**Issue by eg-firebolt** [samirelanduk/firebolt#2]
Hi Sam,

If you are not using the name `firebolt` in PyPI, is there any chance you could delete it/release it so that we might be able to use it?

I work at firebolt (firebolt.io) and I am working on an SDK for our product that we hope to open source for end users.

Thanks for your consideration.

**Comment by samirelanduk** [comment]
Sorry for the delay in responding - I have just replied to your email from last week.
